Repository Foot-Log/footlog-client, pull requests merged in 2024-09, with the labels that each got.

#38 Feat/#25/login/kakao login
  footlog/package-lock.json
  footlog/package.json
  footlog/src/api/api.ts
  footlog/src/app/layout.tsx
  footlog/src/app/user/kakao/callback/page.tsx
  footlog/src/components/common/BigLocationCard.tsx
  footlog/src/components/common/LocationCard.tsx
  footlog/src/components/home/list/ListHeader.tsx
  footlog/src/components/login/LoginBtn.tsx
  footlog/src/hooks/login/usePostLogin.ts
  footlog/src/types/common/CommonTypes.ts
  footlog/src/types/common/Response.ts
  footlog/src/types/login/loginProps.ts
  footlog/src/utils/ReactQueryProvider.tsx
  footlog/src/utils/removeToken.ts
  footlog/src/utils/token.ts
  footlog/src/utils/useSetInterceptors.ts
  footlog/yarn.lock
Labels: feat

#39 [Refactor] 로그인 data 반환값 수정
  footlog/src/hooks/login/useGetLogin.ts
  footlog/src/types/login/loginProps.ts
Labels: refactor

#42 Feat/#32/onboarding/prefer api
  footlog/src/api/onboarding/api.ts
  footlog/src/api/onboarding/getRecommend.ts
  footlog/src/api/onboarding/postPreferKeyword.ts
  footlog/src/app/onboarding/step3/page.tsx
  footlog/src/app/onboarding/step4/page.tsx
  footlog/src/hooks/onboarding/usePostPreferKeyword.ts
Labels: feat

#43 Feat/#34/home/region api
  footlog/package-lock.json
  footlog/package.json
  footlog/src/api/api.ts
  footlog/src/api/getRegions.ts
  footlog/src/api/home/list/getRegionalCourse.ts
  footlog/src/app/(CommonLayout)/home/list/[id]/page.tsx
  footlog/src/components/common/BigLocationCard.tsx
  footlog/src/components/home/RegionalRecommendContainer.tsx
  footlog/src/core/regionsData.ts
  footlog/src/hooks/home/list/useGetRegionalCourse.ts
  footlog/src/hooks/home/useGetRegions.ts
  footlog/src/hooks/login/useGetLogin.ts
  footlog/src/types/common/CommonTypes.ts
  footlog/src/types/common/Response.ts
Labels: feat

#44 Feat/#35/details/course api
  footlog/src/api/home/details/getCourseDetails.ts
  footlog/src/api/home/details/postComplete.ts
  footlog/src/api/home/details/postSave.ts
  footlog/src/app/(CommonLayout)/home/details/[id]/page.tsx
  footlog/src/components/home/details/DetailsHeader.tsx
  footlog/src/components/home/details/FinishBtn.tsx
  footlog/src/components/home/details/ImageContainer.tsx
  footlog/src/components/home/details/InfoContainer.tsx
  footlog/src/hooks/home/details/useGetCourseDetails.ts
  footlog/src/hooks/home/details/usePostComplete.ts
  footlog/src/hooks/home/details/usePostSave.ts
  footlog/src/hooks/list/useInfiniteQuery.ts
  footlog/src/types/home/details/DetailsTypes.ts
Labels: feat

#45 Feat/#36/details/blog api
  footlog/next.config.mjs
  footlog/src/api/home/details/getBlogPosting.ts
  footlog/src/app/(CommonLayout)/home/details/[id]/page.tsx
  footlog/src/app/(CommonLayout)/home/list/[id]/page.tsx
  footlog/src/app/(CommonLayout)/mypage/page.tsx
  footlog/src/app/(CommonLayout)/mypage/save/page.tsx
  footlog/src/components/common/LocationCard/BigLocationCard.tsx
  footlog/src/components/common/LocationCard/LocationCard.tsx
  footlog/src/components/home/details/BlogContainer.tsx
  footlog/src/components/home/details/InfoContainer.tsx
  footlog/src/components/home/search/SearchingResults.tsx
  footlog/src/components/home/search/results/BigLocationCard.tsx
  footlog/src/components/home/search/results/SearchedResults.tsx
  footlog/src/core/blogPostingData.ts
  footlog/src/hooks/home/details/useGetBlogPosting.ts
  footlog/src/hooks/home/details/useGetCourseDetails.ts
  footlog/src/utils/formatDate.ts
  footlog/src/utils/useSetInterceptors.ts
Labels: feat

#47 온보딩 정보 post 바뀐 부분 적용
  footlog/src/api/home/list/getRegionalCourse.ts
  footlog/src/api/onboarding/api.ts
  footlog/src/api/onboarding/getRecommend.ts
  footlog/src/api/onboarding/postPreferKeyword.ts
  footlog/src/app/(CommonLayout)/home/details/[id]/page.tsx
  footlog/src/app/(CommonLayout)/home/list/[id]/page.tsx
  footlog/src/app/(CommonLayout)/home/page.tsx
  footlog/src/app/onboarding/step3/page.tsx
  footlog/src/components/common/CoursesSlider/CoursesSlider.tsx
  footlog/src/components/home/RecommendContainer.tsx
  footlog/src/components/home/details/BlogContainer.tsx
  footlog/src/core/recommendCoursesData.ts
  footlog/src/recoil/atom.ts
  footlog/src/types/common/CommonTypes.ts
  footlog/src/types/home/HomeTypes.ts
  footlog/src/types/home/details/DetailsTypes.ts
Labels: feat, refactor

#48 Feat/#33/home/recommend api
  footlog/src/api/home/getPopularCourse.ts
  footlog/src/api/home/getRegions.ts
  footlog/src/app/(CommonLayout)/home/page.tsx
  footlog/src/components/common/CoursesSlider/CoursesSlider.tsx
  footlog/src/components/common/LocationCard/BigLocationCard.tsx
  footlog/src/hooks/home/useGetPopularCourse.ts
  footlog/src/hooks/home/useGetRegions.ts
Labels: feat

#49 [Feature] 완주한 코스 api 가져오기
  footlog/src/api/log/getCompletedList.ts
  footlog/src/app/(CommonLayout)/log/page.tsx
  footlog/src/components/log/KakaoMap.tsx
  footlog/src/hooks/log/useGetCompletedList.ts
Labels: feat

#50 [Feature] getLogDetails api 연결
  footlog/src/api/log/getLogDetails.ts
  footlog/src/components/log/KakaoMap.tsx
  footlog/src/hooks/log/useGetLogDetails.ts
Labels: feat

#51 [Feature] updateLog api 연결
  footlog/src/api/log/updateLog.ts
  footlog/src/components/log/KakaoMap.tsx
  footlog/src/hooks/log/useUpdateLog.ts
Labels: feat

#53 Feat/#52/log/refetch
  footlog/src/app/(CommonLayout)/home/details/[id]/page.tsx
  footlog/src/components/log/KakaoMap.tsx
Labels: feat

#55 [Feat] 마이페이지 저장 목록, 최근 확인한 코스 api 연결
  footlog/src/api/mypage/getRecentCourseList.ts
  footlog/src/api/mypage/getSaveCourseList.ts
  footlog/src/app/(CommonLayout)/mypage/page.tsx
  footlog/src/app/(CommonLayout)/mypage/save/page.tsx
  footlog/src/components/common/RecentCourseContainer.tsx
  footlog/src/components/mypage/MypageContainer.tsx
  footlog/src/hooks/mypage/useGetRecentCourseList.ts
  footlog/src/hooks/mypage/useGetSaveCourseList.ts
Labels: feat

#57 Design/#54/loading/UI
  footlog/src/app/loading.tsx
Labels: design

#58 Feat/#46/search/search api
  footlog/src/api/common/getPopularCourse.ts
  footlog/src/api/common/getRecentCourse.ts
  footlog/src/api/home/search/getCityRegions.ts
  footlog/src/api/home/search/getRecentSearch.ts
  footlog/src/api/home/search/getSearchResult.ts
  footlog/src/api/home/search/patchRecentSearch.ts
  footlog/src/app/(CommonLayout)/home/details/[id]/page.tsx
  footlog/src/app/(CommonLayout)/home/list/[id]/page.tsx
  footlog/src/app/(CommonLayout)/home/page.tsx
  footlog/src/app/(CommonLayout)/home/search/page.tsx
  footlog/src/app/(CommonLayout)/home/search/results/page.tsx
  footlog/src/app/(CommonLayout)/mypage/page.tsx
  footlog/src/app/onboarding/step4/page.tsx
  footlog/src/components/common/CoursesSlider/CoursesSlider.tsx
  footlog/src/components/common/LocationCard/LocationCard.tsx
  footlog/src/components/common/RecentCourseContainer.tsx
  footlog/src/components/common/RecentCourseContainer/RecentCourseContainer.tsx
  footlog/src/components/home/RegionalRecommendContainer.tsx
  footlog/src/components/home/details/BlogContainer.tsx
  footlog/src/components/home/search/PopularContainer.tsx
  footlog/src/components/home/search/RecentSearchContainer.tsx
  footlog/src/components/home/search/RegionCard.tsx
  footlog/src/components/home/search/SearchHeader.tsx
  footlog/src/components/home/search/SearchingResults.tsx
  footlog/src/components/home/search/results/SearchedResults.tsx
  footlog/src/components/log/KakaoMap.tsx
  footlog/src/core/courseDetailsData.ts
  footlog/src/core/locationData.ts
  footlog/src/core/popularCourseData.ts
  footlog/src/core/recentSearchData.ts
  footlog/src/hooks/common/useGetPopularCourse.ts
  footlog/src/hooks/common/useGetRecentCourse.ts
  footlog/src/hooks/home/details/useGetCourseDetails.ts
  footlog/src/hooks/home/search/useGetCityRegions.ts
  footlog/src/hooks/home/search/useGetRecentSearch.ts
  footlog/src/hooks/home/search/useGetSearchResult.ts
  footlog/src/hooks/home/search/usePatchRecentSearch.ts
  footlog/src/hooks/log/useGetCompletedList.ts
  footlog/src/hooks/log/useGetLogDetails.ts
  footlog/src/hooks/mypage/useGetRecentCourseList.ts
  footlog/src/types/common/CommonTypes.ts
  footlog/src/types/home/search/SearchTypes.ts
  footlog/src/utils/filterData.ts
  footlog/src/utils/formatAddress.ts
  footlog/src/utils/formatDate.ts
Labels: feat

#59 [Feature] 기존 로그인 유저의 경우 선호도 코스 api 호출로 라우팅
  footlog/src/hooks/login/useGetLogin.ts
Labels: feat

#61 [Feat] 회원 정보 api 연결
  footlog/src/api/mypage/getUserInfo.ts
  footlog/src/app/(CommonLayout)/mypage/page.tsx
  footlog/src/hooks/mypage/useGetUserInfo.ts
Labels: feat

#62 [Feat] 마이페이지 관련 모든 api 연결 완료
  footlog/src/api/mypage/deleteUser.ts
  footlog/src/app/(CommonLayout)/mypage/page.tsx
  footlog/src/hooks/mypage/useDeleteUser.ts
Labels: feat

#63 Feat/#60/save/save api
  footlog/src/api/home/getRecommend.ts
  footlog/src/api/home/list/getCityCourse.ts
  footlog/src/app/(CommonLayout)/home/details/[id]/page.tsx
  footlog/src/app/(CommonLayout)/home/list/big/[id]/page.tsx
  footlog/src/app/(CommonLayout)/home/list/small/[id]/page.tsx
  footlog/src/app/(CommonLayout)/home/page.tsx
  footlog/src/app/(CommonLayout)/mypage/page.tsx
  footlog/src/app/(CommonLayout)/mypage/save/page.tsx
  footlog/src/app/globals.css
  footlog/src/app/onboarding/step3/page.tsx
  footlog/src/app/onboarding/step4/page.tsx
  footlog/src/components/common/CoursesSlider/CoursesSlider.tsx
  footlog/src/components/common/LocationCard/BigLocationCard.tsx
  footlog/src/components/common/RecentCourseContainer/RecentCourseContainer.tsx
  footlog/src/components/home/RegionalRecommendContainer.tsx
  footlog/src/components/home/details/DetailsHeader.tsx
  footlog/src/components/home/search/PopularContainer.tsx
  footlog/src/components/home/search/RecentSearchContainer.tsx
  footlog/src/components/home/search/SearchingResults.tsx
  footlog/src/components/mypage/MypageContainer.tsx
  footlog/src/components/mypage/SaveCourseContainer.tsx
  footlog/src/hooks/common/useGetPopularCourse.ts
  footlog/src/hooks/home/list/useGetCityCourse.ts
  footlog/src/hooks/home/list/useGetRegionalCourse.ts
  footlog/src/hooks/home/useGetRecommend.ts
  footlog/src/hooks/mypage/useGetSaveCourseList.ts
  footlog/src/recoil/atom.ts
Labels: feat

#64 Feat/#37/list/infinity scroll
  footlog/next.config.mjs
  footlog/src/api/home/details/getCourseDetails.ts
  footlog/src/app/(CommonLayout)/home/details/[id]/page.tsx
  footlog/src/app/(CommonLayout)/home/list/big/[id]/page.tsx
  footlog/src/app/(CommonLayout)/home/list/small/[id]/page.tsx
  footlog/src/app/(CommonLayout)/home/search/results/page.tsx
  footlog/src/app/(CommonLayout)/mypage/page.tsx
  footlog/src/app/globals.css
  footlog/src/components/common/LocationCard/BigLocationCard.tsx
  footlog/src/components/common/LocationCard/LocationCard.tsx
  footlog/src/components/common/RecentCourseContainer/RecentCourseContainer.tsx
  footlog/src/components/home/details/DetailsHeader.tsx
  footlog/src/components/home/details/InfoContainer.tsx
  footlog/src/components/home/search/RecentSearchContainer.tsx
  footlog/src/components/home/search/results/SearchedResults.tsx
  footlog/src/components/log/MarkerModal.tsx
  footlog/src/hooks/common/useInfiniteScroll.ts
  footlog/src/recoil/atom.ts
  footlog/src/types/home/details/DetailsTypes.ts
  footlog/src/utils/highlightSearchTerm.tsx
Labels: feat

#68 Design/#66/deploy/design qa
  footlog/src/app/(CommonLayout)/mypage/page.tsx
  footlog/src/components/log/MarkerModal.tsx
Labels: design

#70 [Feature]: 로그인 api에 redirect uri parameter 추가
  footlog/src/hooks/login/useGetLogin.ts
Labels: feat

#71 Design/#66/deploy/design qa
  footlog/src/app/(CommonLayout)/mypage/page.tsx
  footlog/src/components/log/MarkerModal.tsx
Labels: design

#73 fix : 글 업로드 기능 수정 #72
  footlog/src/components/log/KakaoMap.tsx
Labels: feat, fix

#74 design : 마이페이지 구분선 위치 조정
  footlog/src/app/(CommonLayout)/mypage/page.tsx
  footlog/src/components/mypage/SaveCourseContainer.tsx
Labels: design

#75 [Feature] 회원 탈퇴 모달창, 로그인 후 로딩페이지,
  footlog/public/courseExample.png
  footlog/public/icon/home/details/call.svg
  footlog/public/icon/home/details/clock.svg
  footlog/public/icon/home/details/location.svg
  footlog/public/icon/home/details/price.svg
  footlog/public/icon/home/details/site.svg
  footlog/src/app/(CommonLayout)/home/details/[id]/page.tsx
  footlog/src/app/(CommonLayout)/home/list/big/[id]/page.tsx
  footlog/src/app/(CommonLayout)/home/search/results/page.tsx
  footlog/src/app/(CommonLayout)/mypage/page.tsx
  footlog/src/app/globals.css
  footlog/src/app/loading.tsx
  footlog/src/app/login/page.tsx
  footlog/src/app/onboarding/step4/page.tsx
  footlog/src/app/page.tsx
  footlog/src/components/common/CoursesSlider/CoursesSlider.tsx
  footlog/src/components/common/LocationCard/BigLocationCard.tsx
  footlog/src/components/home/search/results/SearchedResults.tsx
  footlog/src/components/log/KakaoMap.tsx
  footlog/src/components/mypage/ConfirmModal.tsx
  footlog/src/components/mypage/SaveCourseContainer.tsx
  footlog/src/components/onboarding/OnboardingKeywords.tsx
  footlog/src/components/onboarding/OnboardingTitle.tsx
  footlog/src/hooks/common/useSetScreenSize.ts
  footlog/src/hooks/login/useGetLogin.tsx
  footlog/tailwind.config.ts
Labels: feat, refactor, design
